# Naive Bayes

### Concepts Learned:
1. Naive Bayes
    * A Classification Probablistic Machine Learning Model
    * It is only capable of classification and can't produce contious numbers.
    * It is Naive as it does consider order of data
2. Multinomial NB
    * A Version of Naive Bayes that uses only disceerte data.
    * Steps:
        * Calcuate Prior Probability: For each Class count the instance of each class and divided it by number of all instances.
        * Calcuate Likelihood: For each class, calcualte all P(X|C), where X is each feature. Its best to have an Alpha of atleast one in this step. 
        * Afterwards you can begin with prediction.
        * Enter a input. Count the instance ofe each feature in the input. For each class, calcuate the log of its Prior Probability *  Likelihood of each instance that appeared. The class that has highest value is prediction.
3. Gaussian
    * A Version of Naive Bayes that uses only numerical data.
    * Steps:
        * For each feature, create a Gaussian curve by finding each feature's variation and mean.
        * Calcuate Prior Probability: For each Class count the instance of each class and divided it by number of all instances.
        * Unlike Multinomial NB, Likelihood is not calcuated in the training phase. Instead the Gaussian Curves will be used to find likelihood of each feature in the inference phase.
        *  * Enter a input. Count the instance ofe each feature in the input. For each class, calcuate the log of its Prior Probability *  Likelihood of each instance that appeared(using the Gausian Curve). The class that has highest value is prediction.

Deliverable: Apply GaussianNB to a continuous-feature dataset and MultinomialNB to a text dataset (e.g. 20 Newsgroups). Compare their F1 scores against logistic regression from Week 3. Write a short note on where NB failed and why (look at correlated features).

In [19]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import f1_score, accuracy_score

import pandas as pd
import numpy as np

## MultinomialNB Model

In [10]:
data = pd.read_csv("df_file.csv")
data.head()

                                                Text  Label
0  Budget to set scene for election\n \n Gordon B...      0
1  Army chiefs in regiments decision\n \n Militar...      0
2  Howard denies split over ID cards\n \n Michael...      0
3  Observers to monitor UK election\n \n Minister...      0
4  Kilroy names election seat target\n \n Ex-chat...      0

In [13]:
X_train, X_test, y_train, y_test = train_test_split(data['Text'], data['Label'], shuffle=True, test_size=0.2)

In [11]:
pipeline = Pipeline([
    ("Vectorizer", TfidfVectorizer()),
    ("Model", MultinomialNB(alpha=1.0))
])

In [14]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('Vectorizer', TfidfVectorizer()), ('Model', MultinomialNB())])

In [21]:
y_pred = pipeline.predict(X_test)
f = f1_score(y_true=y_test, y_pred=y_pred, average="macro")
a = accuracy_score(y_true=y_test, y_pred=y_pred)


print(f"F1 Score: {f}")
print(f"Accuracy: {a*100}%")

F1 Score: 0.9667706054873484
Accuracy: 96.85393258426967%

# GaussianNB


For this step, I am going to compare same dataset as before from Deliverable #3 and compare how well GaussianNB to Logestic Regresssion.

In [ ]:
X,y = load_breast_cancer(return_X_y=True)
X1_train, X2_test, y1_train, y2_test = train_test_split(X,y, test_size=0.2, shuffle=True)

In [23]:
model = GaussianNB()
model.fit(X1_train, y1_train)

GaussianNB()

In [31]:
data = load_breast_cancer(as_frame=True).frame
data.corr()

                         mean radius  ...    target
mean radius                 1.000000  ... -0.730029
mean texture                0.323782  ... -0.415185
mean perimeter              0.997855  ... -0.742636
mean area                   0.987357  ... -0.708984
mean smoothness             0.170581  ... -0.358560
mean compactness            0.506124  ... -0.596534
mean concavity              0.676764  ... -0.696360
mean concave points         0.822529  ... -0.776614
mean symmetry               0.147741  ... -0.330499
mean fractal dimension     -0.311631  ...  0.012838
radius error                0.679090  ... -0.567134
texture error              -0.097317  ...  0.008303
perimeter error             0.674172  ... -0.556141
area error                  0.735864  ... -0.548236
smoothness error           -0.222600  ...  0.067016
compactness error           0.206000  ... -0.292999
concavity error             0.194204  ... -0.253730
concave points error        0.376169  ... -0.408042
symmetry error             -0.104321  ...  0.006522
fractal dimension error    -0.042641  ... -0.077972
worst radius                0.969539  ... -0.776454
worst texture               0.297008  ... -0.456903
worst perimeter             0.965137  ... -0.782914
worst area                  0.941082  ... -0.733825
worst smoothness            0.119616  ... -0.421465
worst compactness           0.413463  ... -0.590998
worst concavity             0.526911  ... -0.659610
worst concave points        0.744214  ... -0.793566
worst symmetry              0.163953  ... -0.416294
worst fractal dimension     0.007066  ... -0.323872
target                     -0.730029  ...  1.000000

[31 rows x 31 columns]

In [24]:
y_pred = model.predict(X2_test)

f = f1_score(y_true=y2_test, y_pred=y_pred, average="macro")
a = accuracy_score(y_true=y2_test, y_pred=y_pred)


print(f"F1 Score: {f}")
print(f"Accuracy: {a*100}%")

F1 Score: 0.9535338713621913
Accuracy: 95.6140350877193%

The Main Problem with Naive Bayes is that it assume everything is independent. This causes problems when your datasets contains indpendent varibales with high correlation.

Say you have a dataset that has "Body Temperature" and "Fever Likelness". Those 2 features are high correlated and represent the same signal. However, an NB Model doesn't know with that, and treat both of those featues are completely independent. This leads to the model double counting that singal, giving the signal more weight and effect in the model, than it should.